<a href="https://colab.research.google.com/github/darya-kulikova1988/Python-Jupiter/blob/main/Copy_of_analytics_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

# Задание 1

Задание: 
1.	Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
2.	Считать данные с помощью pandas
3.	Вывести на экран первые 5 строк

In [6]:
df = pd.read_csv("laptop_price.csv", encoding="latin-1")
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

1.1 Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU

In [ ]:
def preprocess(x):
    return x.split()[0]

In [ ]:
df["Cpu_Company"] = df["Cpu"].apply(lambda x: x.split()[0])

In [ ]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [ ]:
def mem_value(x):
    if x.split()[0].endswith('GB'):
        res = x.split()[0].replace('GB','')
    elif x.split()[0].endswith('TB'):
        res = float(x.split()[0].replace('TB','')) * 1024
    return int(res)

In [ ]:
df['Memory_Amount'] = df['Memory'].apply(mem_value)

In [ ]:
df

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Type,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,SSD,128
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,FlashStorage,128
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,SSD,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,SSD,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,SSD,256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Intel,SSD,128
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Intel,SSD,512
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Intel,FlashStorage,64
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Intel,HDD,1024
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Intel,HDD,500

1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др.)

In [ ]:
df['Memory_Type'] = df['Memory'].apply(lambda x: x.replace(' ', '').split('B')[-1])
df.head()

1.4 Удалите признаки Memory и ScreenResolution

In [ ]:
df.drop(columns=['Memory','ScreenResolution'], inplace=True)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Type,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,SSD,128
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,FlashStorage,128
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,SSD,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,SSD,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,SSD,256

---
# Задание 2

2.1 Создайте признак SSD, который изначально равен 0

In [ ]:
df["SSD"] = 0
df.head()

In [ ]:
df["Memory_Type"].unique()

array(['SSD', 'FlashStorage', 'HDD', 'Hybrid'], dtype=object)

2.2 Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [ ]:
df.loc[df['Memory_Type'] == 'SSD', 'SSD'] = 1
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Type,Memory_Amount,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,SSD,128,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,FlashStorage,128,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,SSD,256,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,SSD,512,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,SSD,256,1

2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [ ]:
df["Weight"] = df["Weight"].str.replace('kg', '')

In [ ]:
df["Weight"] = df["Weight"].astype("float")

In [ ]:
df["Weight"]

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: Weight, Length: 1303, dtype: float64

# Задание 3

Создайте датафрейм с клиентами:

```python
clients = pd.DataFrame({
  'client_id': [45, 32, 67, 33, 43], 
  'laptop_id': [506, 398, 710, 120, 1999]
})
```

In [ ]:
clients = pd.DataFrame({
  'client_id': [45, 32, 67, 33, 43], 
  'laptop_id': [506, 398, 710, 120, 1999]
})

3.1 Присоедините к таблице clients данные по ноутбукам через метод join

Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

laptop_id - это индексы датафрейма с ноутбуками

In [ ]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [ ]:
client_lap_id = clients.set_index('laptop_id')
joined = client_lap_id.join(df)
joined

,client_id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
laptop_id,,,,,,,,,,,,,,
506,45,513.0,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD + 1TB HDD,Intel HD Graphics 620,Windows 10,2kg,1224.0
398,32,405.0,Dell,Precision M5520,Workstation,15.6,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia Quadro M1200,Windows 10,1.78kg,2712.0
710,67,718.0,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows 10,2.5kg,1249.0
120,33,123.0,Acer,Spin 3,Notebook,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.1kg,479.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3.2 Присоедините к таблице clients данные по ноутбукам через метод merge

In [ ]:
client_lap_id = clients.set_index('laptop_id')
joined = client_lap_id.join(df.set_index("laptop_ID"), how="inner")
joined

,client_id,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
506,45,Lenovo,ThinkPad L570,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.3kg,911.00
710,67,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,1366x768,AMD A12-Series 9720P 3.6GHz,8GB,1TB HDD,AMD Radeon R7,Windows 10,2.2kg,429.00
120,33,Dell,Inspiron 7570,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,256GB SSD + 1TB HDD,Nvidia GeForce 940MX,Windows 10,2.16kg,1130.33

In [ ]:
df['laptop_id'] = df.index

In [ ]:
merged = clients.merge(df, on='laptop_id')
merged

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,45,506,513,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD + 1TB HDD,Intel HD Graphics 620,Windows 10,2kg,1224.0
1,32,398,405,Dell,Precision M5520,Workstation,15.6,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia Quadro M1200,Windows 10,1.78kg,2712.0
2,67,710,718,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050 Ti,Windows 10,2.5kg,1249.0
3,33,120,123,Acer,Spin 3,Notebook,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.1kg,479.0

# Задание 4

4.1 Найдите среднюю стоимость ноутбуков в зависимости от компании производителя
Отсортируйте от меньшей стоимости к большей

In [ ]:
df.groupby('Company').agg({'Price_euros': 'mean'}).sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [ ]:
df.groupby("Cpu_Company").agg({"Price_euros": ["min", "mean", "max"]})

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Intel             174.0  1152.214145  6099.0
Samsung           659.0   659.000000   659.0

4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [ ]:
df.isna().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
laptop_id           0
Cpu_Company         0
dtype: int64

In [ ]:
df.pivot_table(
    index='Cpu_Company',
    columns='Ram',
    aggfunc='count',
    values='Price_euros',
    fill_value=0
)

Ram          12GB  16GB  24GB  2GB  32GB  4GB  64GB  6GB  8GB
Cpu_Company
AMD             2     3     0    1     0   31     0   13   12
Intel          23   197     3   21    17  343     1   28  607
Samsung         0     0     0    0     0    1     0    0    0

4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [ ]:
df.pivot_table(
    index='OpSys',
    columns='Memory_Amount',
    aggfunc='mean',
    values='Price_euros'
)

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
OpSys,,,,,,,,,,,,,
Android,NaN,NaN,NaN,434.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chrome OS,NaN,305.38,412.454545,774.333333,1275.000000,NaN,NaN,1559.000000,NaN,NaN,2199.000000,NaN,NaN
Linux,NaN,NaN,NaN,NaN,742.250000,NaN,NaN,811.638125,389.056364,NaN,NaN,581.401290,NaN
Mac OS X,NaN,NaN,NaN,NaN,1099.000000,NaN,NaN,1311.994000,NaN,NaN,1222.000000,NaN,NaN
No OS,NaN,NaN,NaN,NaN,562.140000,NaN,NaN,782.989286,404.675385,NaN,1098.500000,540.539600,594.0000
Windows 10,2249.0,NaN,270.001471,499.716000,1026.489167,1073.5,3100.0,1334.456872,664.717647,NaN,1911.985285,904.827906,666.9475
Windows 10 S,NaN,NaN,NaN,308.995000,1039.000000,NaN,NaN,1668.950000,NaN,NaN,2589.000000,NaN,NaN
Windows 7,NaN,NaN,NaN,NaN,1320.323333,1199.0,NaN,1846.466800,924.048333,1002.0,2235.396667,1539.666667,NaN
macOS,NaN,NaN,NaN,NaN,1119.315000,NaN,NaN,1600.370000,NaN,NaN,2180.870000,NaN,NaN

In [ ]:
pd.crosstab(
    index=df["OpSys"],
    columns=df["Memory_Amount"],
    aggfunc="mean",
    values=df["Price_euros"]
)

Memory_Amount,8,16,32,64,128,180,240,256,500,508,512,1024,2048
OpSys,,,,,,,,,,,,,
Android,NaN,NaN,NaN,434.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chrome OS,NaN,305.38,412.454545,774.333333,1275.000000,NaN,NaN,1559.000000,NaN,NaN,2199.000000,NaN,NaN
Linux,NaN,NaN,NaN,NaN,742.250000,NaN,NaN,811.638125,389.056364,NaN,NaN,581.401290,NaN
Mac OS X,NaN,NaN,NaN,NaN,1099.000000,NaN,NaN,1311.994000,NaN,NaN,1222.000000,NaN,NaN
No OS,NaN,NaN,NaN,NaN,562.140000,NaN,NaN,782.989286,404.675385,NaN,1098.500000,540.539600,594.0000
Windows 10,2249.0,NaN,270.001471,499.716000,1026.489167,1073.5,3100.0,1334.456872,664.717647,NaN,1911.985285,904.827906,666.9475
Windows 10 S,NaN,NaN,NaN,308.995000,1039.000000,NaN,NaN,1668.950000,NaN,NaN,2589.000000,NaN,NaN
Windows 7,NaN,NaN,NaN,NaN,1320.323333,1199.0,NaN,1846.466800,924.048333,1002.0,2235.396667,1539.666667,NaN
macOS,NaN,NaN,NaN,NaN,1119.315000,NaN,NaN,1600.370000,NaN,NaN,2180.870000,NaN,NaN

In [ ]:
df.groupby(["OpSys", "Memory_Amount"]).agg({"Price_euros": "mean"}).unstack("Memory_Amount").fillna(0)

              Price_euros                                               \
Memory_Amount        8       16          32          64           128
OpSys
Android               0.0    0.00    0.000000  434.000000     0.000000
Chrome OS             0.0  305.38  412.454545  774.333333  1275.000000
Linux                 0.0    0.00    0.000000    0.000000   742.250000
Mac OS X              0.0    0.00    0.000000    0.000000  1099.000000
No OS                 0.0    0.00    0.000000    0.000000   562.140000
Windows 10         2249.0    0.00  270.001471  499.716000  1026.489167
Windows 10 S          0.0    0.00    0.000000  308.995000  1039.000000
Windows 7             0.0    0.00    0.000000    0.000000  1320.323333
macOS                 0.0    0.00    0.000000    0.000000  1119.315000

                                                                             \
Memory_Amount    180     240          256         500     508          512
OpSys
Android           0.0     0.0     0.000000    0.000000     0.0     0.000000
Chrome OS         0.0     0.0  1559.000000    0.000000     0.0  2199.000000
Linux             0.0     0.0   811.638125  389.056364     0.0     0.000000
Mac OS X          0.0     0.0  1311.994000    0.000000     0.0  1222.000000
No OS             0.0     0.0   782.989286  404.675385     0.0  1098.500000
Windows 10     1073.5  3100.0  1334.456872  664.717647     0.0  1911.985285
Windows 10 S      0.0     0.0  1668.950000    0.000000     0.0  2589.000000
Windows 7      1199.0     0.0  1846.466800  924.048333  1002.0  2235.396667
macOS             0.0     0.0  1600.370000    0.000000     0.0  2180.870000


Memory_Amount         1024      2048
OpSys
Android           0.000000    0.0000
Chrome OS         0.000000    0.0000
Linux           581.401290    0.0000
Mac OS X          0.000000    0.0000
No OS           540.539600  594.0000
Windows 10      904.827906  666.9475
Windows 10 S      0.000000    0.0000
Windows 7      1539.666667    0.0000
macOS             0.000000    0.0000

# Задание 5

5.1 Ноутбуков каких компаний и с каким процессором больше?

In [ ]:
pd.crosstab(
    index=df["Company"],
    columns=df["Cpu_Company"]
)

Cpu_Company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

5.2 С каким типом памяти и с каким объемом памяти больше ноутбуков?

In [ ]:
pd.crosstab(
    index=df["Memory_Type"],
    columns=df["Memory_Amount"]
)

KeyError: ignored